### ISSUE TITLE
mjml's font-size-0px hack makes the cleverreach drag and drop editor unusable (+ workaround)

### ISSUE THREAD

**Issue by gp0** [vielhuber/mjml2cr#1]
When adding elements via drag and drop to an imported template on cleverreach.com, the added element has a height of 0 px (because of mjml's font-size: 0px on the td).

A workaround is to add:

`<mj-style>
.mce-content-body {
        font-size: 13px;
      }
</mj-style>
`

to ` <mj-head>`, the mc-content-body class should only be present in the editor view and not in the resulting email itself, so adding that should be harmless.

**Comment by vielhuber** [comment]
Thanks for reporting, this is now fixed in `v2.0.9`.
Interestingly the new CleverReach editor works without this hack, but I've included it anyway (since the editor seems to be still in beta).
