### ISSUE TITLE
Conten that is placed inside of mj-hero element is not editable in Clever Reach

### ISSUE THREAD

**Issue by creationell** [vielhuber/mjml2cr#2]
I tried mj-hero in my last template unfortunately I can'T edit text or pictures that are placed within mj-hero element in cleverreach after uploading .zip file. All other elements in the template are editable as usual.  Is there anything I should do to get it work?

mjmlhelper v.2.0.7.
mjml 4.11.0

**Comment by vielhuber** [comment]
Hello, thanks for your feedback.
mj-hero should now be supported in `v2.0.8`.
Just run `npm update`.
